version: '3'
services:
  recaptcha:
    build:
      context: .
    ports:
      - "8880:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - INVISIBLE_SITE_KEY=${INVISIBLE_SITE_KEY}
      - INVISIBLE_SECRET_KEY=${INVISIBLE_SECRET_KEY}
      - V3_SITE_KEY=${V3_SITE_KEY}
      - V3_SECRET_KEY=${V3_SECRET_KEY}
